require:
  - rubocop-rails

# Enable all new cops by default

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - spec/dummy/bin/*
    - spec/dummy/db/schema.rb

# Disable not wanted cops

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Rails/ContentTag:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false

# Prefer to use brackets on symbol arrays

Style/SymbolArray:
  EnforcedStyle: brackets

# Prefer to use always lambda literals (->)

Style/Lambda:
  EnforcedStyle: literal
